name: Publish NuGet Package (Legacy API Key)

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v0.3.0-beta
  release:
    types: [published]
  workflow_dispatch:  # Allow manual trigger

# NOTE: This workflow uses the legacy API key approach.
# You must create a repository secret named NUGET_API_KEY with your NuGet.org API key.
# To create an API key: https://www.nuget.org/account/apikeys

env:
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ContosoMCP/ContosoMCP.csproj

      - name: Build
        run: dotnet build ContosoMCP/ContosoMCP.csproj --configuration Release --no-restore

      - name: Pack
        run: dotnet pack ContosoMCP/ContosoMCP.csproj --configuration Release --no-build --output ./nupkg

      - name: Publish to NuGet.org (Legacy API Key)
        run: |
          dotnet nuget push ./nupkg/*.nupkg \
            --api-key ${{ env.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate
